language: elixir
elixir: 1.10
otp_release: 22.0
services:
  - postgresql
jobs:
  include:
    - stage: test
      elixir: 1.7
      otp_release: 20.0
      script: &test_scripts
        - mix test
        - MIX_ENV=test mix credo --ignore design.tagtodo
        - mix dialyzer --halt-exit-status
    - stage: test
      elixir: 1.8
      script: *test_scripts
    - stage: test
      script: *test_scripts
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: mix hex.publish --yes
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
