language: elixir
elixir: 1.8
otp_release: 22.0
jobs:
  include:
    - stage: test
      elixir: 1.6
      otp_release: 20.0
      script: &test_scripts
        - mix test
        - MIX_ENV=test mix credo --ignore design.tagtodo
    - stage: test
      script: *test_scripts
    - stage: deploy
      script: skip
      deploy:
        provider: script
        script: mix hex.publish --yes
        skip_cleanup: true
        on:
          tags: true
          all_branches: true